// Generated by gencpp from file gtest_car/AddTwoInts.msg
// DO NOT EDIT!


#ifndef GTEST_CAR_MESSAGE_ADDTWOINTS_H
#define GTEST_CAR_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <gtest_car/AddTwoIntsRequest.h>
#include <gtest_car/AddTwoIntsResponse.h>


namespace gtest_car
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace gtest_car


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gtest_car::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::gtest_car::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::gtest_car::AddTwoInts > {
  static const char* value()
  {
    return "gtest_car/AddTwoInts";
  }

  static const char* value(const ::gtest_car::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::gtest_car::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::gtest_car::AddTwoInts > 
template<>
struct MD5Sum< ::gtest_car::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gtest_car::AddTwoInts >::value();
  }
  static const char* value(const ::gtest_car::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gtest_car::AddTwoIntsRequest> should match 
// service_traits::DataType< ::gtest_car::AddTwoInts > 
template<>
struct DataType< ::gtest_car::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::gtest_car::AddTwoInts >::value();
  }
  static const char* value(const ::gtest_car::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gtest_car::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::gtest_car::AddTwoInts > 
template<>
struct MD5Sum< ::gtest_car::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gtest_car::AddTwoInts >::value();
  }
  static const char* value(const ::gtest_car::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gtest_car::AddTwoIntsResponse> should match 
// service_traits::DataType< ::gtest_car::AddTwoInts > 
template<>
struct DataType< ::gtest_car::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::gtest_car::AddTwoInts >::value();
  }
  static const char* value(const ::gtest_car::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GTEST_CAR_MESSAGE_ADDTWOINTS_H
