# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from simulator_prototype/Environment.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Environment(genpy.Message):
  _md5sum = "c7b07d3af6ed0820d5cb2f920af3dd4f"
  _type = "simulator_prototype/Environment"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool paused
float64 latitude
float64 longitude
float64 meanWindSpeed
float64 meanWindDirection
float64 meanCurrentSpeed
float64 meanCurrentDirection"""
  __slots__ = ['paused','latitude','longitude','meanWindSpeed','meanWindDirection','meanCurrentSpeed','meanCurrentDirection']
  _slot_types = ['bool','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       paused,latitude,longitude,meanWindSpeed,meanWindDirection,meanCurrentSpeed,meanCurrentDirection

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Environment, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.paused is None:
        self.paused = False
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.meanWindSpeed is None:
        self.meanWindSpeed = 0.
      if self.meanWindDirection is None:
        self.meanWindDirection = 0.
      if self.meanCurrentSpeed is None:
        self.meanCurrentSpeed = 0.
      if self.meanCurrentDirection is None:
        self.meanCurrentDirection = 0.
    else:
      self.paused = False
      self.latitude = 0.
      self.longitude = 0.
      self.meanWindSpeed = 0.
      self.meanWindDirection = 0.
      self.meanCurrentSpeed = 0.
      self.meanCurrentDirection = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B6d().pack(_x.paused, _x.latitude, _x.longitude, _x.meanWindSpeed, _x.meanWindDirection, _x.meanCurrentSpeed, _x.meanCurrentDirection))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 49
      (_x.paused, _x.latitude, _x.longitude, _x.meanWindSpeed, _x.meanWindDirection, _x.meanCurrentSpeed, _x.meanCurrentDirection,) = _get_struct_B6d().unpack(str[start:end])
      self.paused = bool(self.paused)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B6d().pack(_x.paused, _x.latitude, _x.longitude, _x.meanWindSpeed, _x.meanWindDirection, _x.meanCurrentSpeed, _x.meanCurrentDirection))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 49
      (_x.paused, _x.latitude, _x.longitude, _x.meanWindSpeed, _x.meanWindDirection, _x.meanCurrentSpeed, _x.meanCurrentDirection,) = _get_struct_B6d().unpack(str[start:end])
      self.paused = bool(self.paused)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B6d = None
def _get_struct_B6d():
    global _struct_B6d
    if _struct_B6d is None:
        _struct_B6d = struct.Struct("<B6d")
    return _struct_B6d
