#Mass matrix M_rb[6x6]
m_11: 5002.6 # kg
m_12: 0 #kg
m_13: 0 #kg
m_14: 0 #kg
m_15: -1260.7 #kg
m_16: 0 #kg

m_21: 0 #kg
m_22: 5002.6 #kg
m_23: 0 #kg
m_24: 1260.7 #kg
m_25: 0 #kg
m_26: 0 #kg

m_31: 0 # kg
m_32: 0 #kg
m_33: 5002.6 #kg
m_34: 0 #kg
m_35: 0 #kg
m_36: 0 #kg

m_41: 0 # kg
m_42: 1260.7 #kg
m_43: 0 #kg
m_44: 4280.2 #kg
m_45: 0 #kg
m_46: 0 #kg

m_51: -1260.7 # kg
m_52: 0 #kg
m_53: 0 #kg
m_54: 0 #kg
m_55: 19535.6 #kg
m_56: 0 #kg

m_61: 0 # kg
m_62: 0 #kg
m_63: 0 #kg
m_64: 0 #kg
m_65: 0 #kg
m_66: 19217.9 #kg

#Added mass matrix M_a[6x6]
X_u_dot: 439.7 # kg
X_v_dot: 0 #kg
X_w_dot: 0 #kg
X_p_dot: 0 #kg
X_q_dot: 0 #kg
X_r_dot: 0 #kg

Y_u_dot: 0 # kg
Y_v_dot: 1774.3 #kg
Y_w_dot: 0 #kg
Y_p_dot: 1057.8 #kg
Y_q_dot: 0 #kg
Y_r_dot: 400.6 #kg

Z_u_dot: 0 # kg
Z_v_dot: 0 #kg
Z_w_dot: 13722.8 #kg
Z_p_dot: 0 #kg
Z_q_dot: 3737.4 #kg
Z_r_dot: 0 #kg

K_u_dot: 0 # kg
K_v_dot: 843.7 #kg
K_w_dot: 0 #kg
K_p_dot: 2131 #kg
K_q_dot: 0 #kg
K_r_dot: 198.7 #kg

M_u_dot: 0 # kg
M_v_dot: 0 #kg
M_w_dot: 7605.1 #kg
M_p_dot: 0 #kg
M_q_dot: 37153.1 #kg
M_r_dot: 0 #kg

N_u_dot: 0 # kg
N_v_dot: 361.5 #kg
N_w_dot: 0 #kg
N_p_dot: 106.8 #kg
N_q_dot: 0 #kg
N_r_dot: 5176.6 #kg

# Center of gravity
x_g: 0.0
y_g: 0.0

# Linear damping terms
X_u: -268.09
X_v: 0.0
Y_v: -1083.3
Y_r: 0
N_v: 0
N_r: -12810
K_p: -200.3
K_r: 0
Z_q: 0
Z_w: -10000
M_q: -300000
M_r: 0

# Restoring forces
Z_z: -146197.67
Z_theta: 9002.86
K_phi: -47648.48
M_z: 9002.86
M_theta: -423188.66

# Nonlinear damping terms
X_uu: -135
X_uuu: 0
X_vv: 0
X_vvv: 0
Y_vv: -2000
Y_vvv: -1500
Y_rr: 0
Y_rrr: 0.0
Y_rv: 0
Y_vr: 0
N_rr:  -5000
N_rrr: -3224
N_vv: 0
N_vvv: 0.0
N_rv: 0
N_vr: 0
M_qq: 0

K_thruster: 0.000013888889

dt: 0.01
