// Generated by gencpp from file simulator_prototype/Gps.msg
// DO NOT EDIT!


#ifndef SIMULATOR_PROTOTYPE_MESSAGE_GPS_H
#define SIMULATOR_PROTOTYPE_MESSAGE_GPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace simulator_prototype
{
template <class ContainerAllocator>
struct Gps_
{
  typedef Gps_<ContainerAllocator> Type;

  Gps_()
    : header()
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , heading(0.0)
    , headingRate(0.0)
    , track(0.0)
    , speed(0.0)  {
    }
  Gps_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , heading(0.0)
    , headingRate(0.0)
    , track(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef double _heading_type;
  _heading_type heading;

   typedef double _headingRate_type;
  _headingRate_type headingRate;

   typedef double _track_type;
  _track_type track;

   typedef double _speed_type;
  _speed_type speed;




  typedef boost::shared_ptr< ::simulator_prototype::Gps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator_prototype::Gps_<ContainerAllocator> const> ConstPtr;

}; // struct Gps_

typedef ::simulator_prototype::Gps_<std::allocator<void> > Gps;

typedef boost::shared_ptr< ::simulator_prototype::Gps > GpsPtr;
typedef boost::shared_ptr< ::simulator_prototype::Gps const> GpsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator_prototype::Gps_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator_prototype::Gps_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simulator_prototype

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'simulator_prototype': ['/home/d943/Dropbox/Master/catkin_ws/src/simulator_prototype/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simulator_prototype::Gps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator_prototype::Gps_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator_prototype::Gps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator_prototype::Gps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator_prototype::Gps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator_prototype::Gps_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator_prototype::Gps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fabe52f68c7f92616561ddbc3f435aee";
  }

  static const char* value(const ::simulator_prototype::Gps_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfabe52f68c7f9261ULL;
  static const uint64_t static_value2 = 0x6561ddbc3f435aeeULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator_prototype::Gps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator_prototype/Gps";
  }

  static const char* value(const ::simulator_prototype::Gps_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator_prototype::Gps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 latitude\n\
float64 longitude\n\
float64 altitude\n\
float64 heading\n\
float64 headingRate\n\
float64 track\n\
float64 speed\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::simulator_prototype::Gps_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator_prototype::Gps_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.heading);
      stream.next(m.headingRate);
      stream.next(m.track);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Gps_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator_prototype::Gps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator_prototype::Gps_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "headingRate: ";
    Printer<double>::stream(s, indent + "  ", v.headingRate);
    s << indent << "track: ";
    Printer<double>::stream(s, indent + "  ", v.track);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_PROTOTYPE_MESSAGE_GPS_H
