// Generated by gencpp from file environment/obstacleCmd.msg
// DO NOT EDIT!


#ifndef ENVIRONMENT_MESSAGE_OBSTACLECMD_H
#define ENVIRONMENT_MESSAGE_OBSTACLECMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace environment
{
template <class ContainerAllocator>
struct obstacleCmd_
{
  typedef obstacleCmd_<ContainerAllocator> Type;

  obstacleCmd_()
    : cmdSpecifier()
    , receiverID()
    , x(0.0)
    , y(0.0)
    , psi(0.0)  {
    }
  obstacleCmd_(const ContainerAllocator& _alloc)
    : cmdSpecifier(_alloc)
    , receiverID(_alloc)
    , x(0.0)
    , y(0.0)
    , psi(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cmdSpecifier_type;
  _cmdSpecifier_type cmdSpecifier;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _receiverID_type;
  _receiverID_type receiverID;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _psi_type;
  _psi_type psi;




  typedef boost::shared_ptr< ::environment::obstacleCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::environment::obstacleCmd_<ContainerAllocator> const> ConstPtr;

}; // struct obstacleCmd_

typedef ::environment::obstacleCmd_<std::allocator<void> > obstacleCmd;

typedef boost::shared_ptr< ::environment::obstacleCmd > obstacleCmdPtr;
typedef boost::shared_ptr< ::environment::obstacleCmd const> obstacleCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::environment::obstacleCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::environment::obstacleCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace environment

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'environment': ['/home/d943/Dropbox/Master/catkin_ws/src/environment/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::environment::obstacleCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::environment::obstacleCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::environment::obstacleCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::environment::obstacleCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::environment::obstacleCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::environment::obstacleCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::environment::obstacleCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73d0006ff3da56034acc0179aa503208";
  }

  static const char* value(const ::environment::obstacleCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73d0006ff3da5603ULL;
  static const uint64_t static_value2 = 0x4acc0179aa503208ULL;
};

template<class ContainerAllocator>
struct DataType< ::environment::obstacleCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "environment/obstacleCmd";
  }

  static const char* value(const ::environment::obstacleCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::environment::obstacleCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string cmdSpecifier\n\
string receiverID\n\
float64 x\n\
float64 y\n\
float64 psi\n\
";
  }

  static const char* value(const ::environment::obstacleCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::environment::obstacleCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmdSpecifier);
      stream.next(m.receiverID);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.psi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct obstacleCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::environment::obstacleCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::environment::obstacleCmd_<ContainerAllocator>& v)
  {
    s << indent << "cmdSpecifier: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cmdSpecifier);
    s << indent << "receiverID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.receiverID);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "psi: ";
    Printer<double>::stream(s, indent + "  ", v.psi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ENVIRONMENT_MESSAGE_OBSTACLECMD_H
